import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav";
import NotificationWrapper from "@/components/notification";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links = [
  { href: '/', label: 'Dashboard' },
  { href: '/tracking', label: 'Tracking' },
  { href: '/analytics', label: 'Analytics' },
]

const trackingOptions = [
  { value: "shipments", label: "Shipments" },
  { value: "inventory", label: "Inventory" },
  { value: "assets", label: "Assets" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar links={links} trackingOptions={trackingOptions} sideNavContent={<NotificationWrapper />}/>
        {children}
        </body>
    </html>
  );
}
